### ISSUE TITLE
More configuration ability for scrot

### ISSUE THREAD

**Issue by warmwaffles** [dsaltares/glapse#9]
Since scrot is the underlying mechanism, I would love to be able to disable the system beeps and pass which display to capture since I work on a multi head setup.

**Comment by saltares** [comment]
It's been a long time since I touched any glapse code. I don't even have a Linux OS on my home computer anymore... I would gladly welcome a PR with this feature though!

**Comment by warmwaffles** [comment]
I shall see what I can do.

**Comment by warmwaffles** [comment]
7 years old. I think this is probably okay to close 😆
